---
abstract: 'Standard Flowgram Format for Perl'
author:
  - 'Leon Timmermans <leont@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::Kwalitee: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300003, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bio-SFF
requires:
  Carp: 0
  Config: 0
  Const::Fast: 0
  Moo: 0
  Scalar::Util: 0
  Sub::Name: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Bio-SFF
  repository: git://github.com/Leont/bio-sff.git
version: 0.002
